package report

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"acre/ticket"
)

// CodeChange represents a modification in a file.
type CodeChange struct {
	File        string `json:"file"`
	Description string `json:"description"`
}

// RemediationDetails holds the detailed analysis generated by OpenCode.
type RemediationDetails struct {
	UnderstoodIssue         string       `json:"understood_issue"`
	PotentialIssue          string       `json:"potential_issue"`
	Approach                string       `json:"approach"`
	CodeChanges             []CodeChange `json:"code_changes"`
	Recommendations         string       `json:"recommendations"`
	ConfidenceScore         int          `json:"confidence_score"`
	ConfidenceJustification string       `json:"confidence_justification"`
	Solved                  bool         `json:"solved"`
	WroteTests              bool         `json:"wrote_tests"`
}

// Data holds all information needed to generate the report.
type Data struct {
	Ticket         *ticket.Ticket
	Prompt         string
	OpenCodeOutput string
	BuildCommand   string
	BuildExitCode  int
	BuildStdout    string
	BuildStderr    string
	TestCommand    string
	TestExitCode   int
	TestStdout     string
	TestStderr     string
	RepositoryPath string
	Details        *RemediationDetails
	HasDetails     bool
	PullRequestURL string
}

// Generate creates a timestamped run directory and saves all artifacts and the final report.
func Generate(baseRunsDir string, data Data) (string, error) {
	timestamp := time.Now().Format("2006-01-02T15-04-05")
	runDir := filepath.Join(baseRunsDir, timestamp)

	if err := os.MkdirAll(runDir, 0755); err != nil {
		return "", fmt.Errorf("failed to create run directory: %w", err)
	}

	details := data.Details
	hasDetails := data.HasDetails

	// Save the prompt
	if err := os.WriteFile(filepath.Join(runDir, "prompt.txt"), []byte(data.Prompt), 0644); err != nil {
		return "", err
	}

	// Save opencode output
	if err := os.WriteFile(filepath.Join(runDir, "opencode_output.log"), []byte(data.OpenCodeOutput), 0644); err != nil {
		return "", err
	}

	// Save build logs
	buildLogs := fmt.Sprintf("Command: %s\nExit Code: %d\n\nSTDOUT:\n%s\n\nSTDERR:\n%s\n", data.BuildCommand, data.BuildExitCode, data.BuildStdout, data.BuildStderr)
	if err := os.WriteFile(filepath.Join(runDir, "build.log"), []byte(buildLogs), 0644); err != nil {
		return "", err
	}

	// Save test logs
	testLogs := fmt.Sprintf("Command: %s\nExit Code: %d\n\nSTDOUT:\n%s\n\nSTDERR:\n%s\n", data.TestCommand, data.TestExitCode, data.TestStdout, data.TestStderr)
	if err := os.WriteFile(filepath.Join(runDir, "test.log"), []byte(testLogs), 0644); err != nil {
		return "", err
	}

	// Determine Outcome
	outcome := "Success"
	if data.BuildExitCode != 0 {
		outcome = "Failure (Build Failed)"
	} else if data.TestExitCode != 0 {
		outcome = "Failure (Tests Failed)"
	} else if hasDetails && !details.Solved {
		outcome = "Failure (OpenCode was unable to solve the issue)"
	}

	// Generate Detailed Remediation Report Content
	reportContent := ""
	if hasDetails {
		reportContent = fmt.Sprintf(`# Remediation Report

## Ticket Information
* **Ticket ID:** %s
* **Summary:** %s

## OpenCode Incident Analysis
### Understanding of the Issue
%s

### Core Root Cause Identified
%s

### Approach Used to Resolve
%s

### Applied Code Changes
` + formatCodeChanges(details.CodeChanges) + `

### Extra Information
* **Unit Tests Written/Modified:** %t
* **Solved Successfully:** %t

## Validation Execution Logs
* **Build Verification Command:** %s
* **Build Verification Result:** %s
* **Test Verification Command:** %s
* **Test Verification Result:** %s

## Final Status
* **Outcome:** %s

%s`,
			data.Ticket.TicketID,
			data.Ticket.Summary,
			details.UnderstoodIssue,
			details.PotentialIssue,
			details.Approach,
			details.WroteTests,
			details.Solved,
			data.BuildCommand,
			getResultString(data.BuildExitCode),
			data.TestCommand,
			getResultString(data.TestExitCode),
			outcome,
			formatRecommendations(details.Recommendations, details.Solved),
		)
	} else {
		// Fallback if details JSON is missing (e.g. crash before writing)
		reportContent = fmt.Sprintf(`# Remediation Report

## Ticket Information
* **Ticket ID:** %s
* **Summary:** %s

## Validation Execution Logs
* **Build Verification Command:** %s
* **Build Verification Result:** %s
* **Test Verification Command:** %s
* **Test Verification Result:** %s

## Final Status
* **Outcome:** %s

> [!WARNING]
> No structured ` + "`" + `remediation_details.json` + "`" + ` was found in the workspace. OpenCode may have crashed or terminated prematurely.
`,
			data.Ticket.TicketID,
			data.Ticket.Summary,
			data.BuildCommand,
			getResultString(data.BuildExitCode),
			data.TestCommand,
			getResultString(data.TestExitCode),
			outcome,
		)
	}

	if data.PullRequestURL != "" {
		reportContent += fmt.Sprintf("\n## Git & Pull Request Status\n* **Pull Request Link**: [Create or View Pull Request](%s)\n", data.PullRequestURL)
	}

	reportPath := filepath.Join(runDir, "remediation_report.md")
	if err := os.WriteFile(reportPath, []byte(reportContent), 0644); err != nil {
		return "", err
	}

	return runDir, nil
}

func getResultString(exitCode int) string {
	if exitCode == 0 {
		return "Success"
	}
	return "Failure"
}

func formatCodeChanges(changes []CodeChange) string {
	if len(changes) == 0 {
		return "_No files were modified._\n"
	}
	var out string
	for _, c := range changes {
		out += fmt.Sprintf("* **File:** `%s`\n  * **Change:** %s\n", c.File, c.Description)
	}
	return out
}

func formatRecommendations(recs string, solved bool) string {
	if solved || recs == "" {
		return ""
	}
	return fmt.Sprintf("## Recommendations for Manual Remediation\n> [!IMPORTANT]\n> OpenCode was unable to solve the issue automatically. Here are the recommended manual steps:\n>\n%s\n", recs)
}
