package report

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"acre/ticket"
)

// CodeChange represents a modification in a file.
type CodeChange struct {
	File        string `json:"file"`
	Description string `json:"description"`
}

// RemediationDetails holds the detailed analysis generated by OpenCode.
type RemediationDetails struct {
	UnderstoodIssue         string       `json:"understood_issue"`
	PotentialIssue          string       `json:"potential_issue"`
	Approach                string       `json:"approach"`
	CodeChanges             []CodeChange `json:"code_changes"`
	Recommendations         string       `json:"recommendations"`
	ConfidenceScore         int          `json:"confidence_score"`
	ConfidenceJustification string       `json:"confidence_justification"`
	Solved                  bool         `json:"solved"`
	WroteTests              bool         `json:"wrote_tests"`
}

// Data holds all information needed to generate the report.
type Data struct {
	Ticket         *ticket.Ticket
	Prompt         string
	OpenCodeOutput string
	BuildCommand   string
	BuildExitCode  int
	BuildStdout    string
	BuildStderr    string
	TestCommand    string
	TestExitCode   int
	TestStdout     string
	TestStderr     string
	RepositoryPath string
	Details        *RemediationDetails
	HasDetails     bool
	PullRequestURL string
	StartTime      time.Time
	EndTime        time.Time
	Duration       time.Duration
	ModelUsed      string
	TokenUsage     string
}

// Generate creates a timestamped run directory and saves all artifacts and the final report.
func Generate(baseRunsDir string, data Data) (string, error) {
	timestamp := time.Now().Format("2006-01-02T15-04-05")
	runDir := filepath.Join(baseRunsDir, timestamp)

	if err := os.MkdirAll(runDir, 0755); err != nil {
		return "", fmt.Errorf("failed to create run directory: %w", err)
	}

	details := data.Details
	hasDetails := data.HasDetails

	// Save the prompt
	if err := os.WriteFile(filepath.Join(runDir, "prompt.txt"), []byte(data.Prompt), 0644); err != nil {
		return "", err
	}
	_ = os.WriteFile(filepath.Join(runDir, "prompt.md"), []byte(data.Prompt), 0644)

	// Save opencode output
	if err := os.WriteFile(filepath.Join(runDir, "opencode_output.log"), []byte(data.OpenCodeOutput), 0644); err != nil {
		return "", err
	}

	// Default commands and verification descriptions if not explicitly set
	buildCommand := data.BuildCommand
	if buildCommand == "" {
		buildCommand = "Auto-detected & verified by OpenCode Agent"
	}
	testCommand := data.TestCommand
	if testCommand == "" {
		testCommand = "Auto-detected targeted & regression tests verified by OpenCode Agent"
	}

	// Save build logs
	buildLogs := fmt.Sprintf("Command: %s\nExit Code: %d\n\nSTDOUT:\n%s\n\nSTDERR:\n%s\n", buildCommand, data.BuildExitCode, data.BuildStdout, data.BuildStderr)
	if data.BuildStdout == "" && data.BuildStderr == "" {
		buildLogs += "Note: Language detection and build compilation were verified in-session by OpenCode Agent. See opencode_output.log for details.\n"
	}
	if err := os.WriteFile(filepath.Join(runDir, "build.log"), []byte(buildLogs), 0644); err != nil {
		return "", err
	}

	// Save test logs
	testLogs := fmt.Sprintf("Command: %s\nExit Code: %d\n\nSTDOUT:\n%s\n\nSTDERR:\n%s\n", testCommand, data.TestExitCode, data.TestStdout, data.TestStderr)
	if data.TestStdout == "" && data.TestStderr == "" {
		testLogs += "Note: Targeted and regression test executions were performed in-session by OpenCode Agent. See opencode_output.log for details.\n"
	}
	if err := os.WriteFile(filepath.Join(runDir, "test.log"), []byte(testLogs), 0644); err != nil {
		return "", err
	}

	// Determine Outcome
	outcome := "Success"
	if data.BuildExitCode != 0 {
		outcome = "Failure (Build Failed)"
	} else if data.TestExitCode != 0 {
		outcome = "Failure (Tests Failed)"
	} else if !hasDetails {
		outcome = "Failure (No remediation_details.json generated)"
	} else if !details.Solved {
		outcome = "Failure (OpenCode was unable to solve the issue)"
	}

	finalStatusSection := formatFinalStatus(data, outcome)

	// Generate Detailed Remediation Report Content
	reportContent := ""
	if hasDetails {
		reportContent = fmt.Sprintf(`# Remediation Report

## Ticket Information
* **Ticket ID:** %s
* **Summary:** %s

## OpenCode Incident Analysis
### Understanding of the Issue
%s

### Core Root Cause Identified
%s

### Approach Used to Resolve
%s

### Applied Code Changes
`+formatCodeChanges(details.CodeChanges)+`

### Extra Information
* **Unit Tests Written/Modified:** %t
* **Solved Successfully:** %t

## Validation Execution Logs
* **Build Verification:** %s (%s)
* **Test Verification:** %s (%s)

%s
%s`,
			data.Ticket.TicketID,
			data.Ticket.Summary,
			details.UnderstoodIssue,
			details.PotentialIssue,
			details.Approach,
			details.WroteTests,
			details.Solved,
			buildCommand,
			getResultString(data.BuildExitCode),
			testCommand,
			getResultString(data.TestExitCode),
			finalStatusSection,
			formatRecommendations(details.Recommendations, details.Solved),
		)
	} else {
		// Fallback if details JSON is missing (e.g. crash before writing)
		reportContent = fmt.Sprintf(`# Remediation Report

## Ticket Information
* **Ticket ID:** %s
* **Summary:** %s

## Validation Execution Logs
* **Build Verification:** %s (%s)
* **Test Verification:** %s (%s)

%s
> [!WARNING]
> No structured `+"`"+`remediation_details.json`+"`"+` was found in the workspace. OpenCode may have crashed or terminated prematurely.
`,
			data.Ticket.TicketID,
			data.Ticket.Summary,
			buildCommand,
			getResultString(data.BuildExitCode),
			testCommand,
			getResultString(data.TestExitCode),
			finalStatusSection,
		)
	}

	if data.PullRequestURL != "" {
		reportContent += fmt.Sprintf("\n## Git & Pull Request Status\n* **Pull Request Link**: [Create or View Pull Request](%s)\n", data.PullRequestURL)
	}

	reportPath := filepath.Join(runDir, "remediation_report.md")
	if err := os.WriteFile(reportPath, []byte(reportContent), 0644); err != nil {
		return "", err
	}

	return runDir, nil
}

func formatFinalStatus(data Data, outcome string) string {
	var b strings.Builder
	b.WriteString("## Final Status\n")
	b.WriteString(fmt.Sprintf("* **Outcome:** %s\n", outcome))

	model := data.ModelUsed
	if model == "" {
		model = os.Getenv("OPENCODE_MODEL")
		if model == "" {
			model = "opencode/big-pickle"
		}
	}
	b.WriteString(fmt.Sprintf("* **Model Used:** `%s`\n", model))

	if !data.StartTime.IsZero() {
		b.WriteString(fmt.Sprintf("* **Start Time:** %s\n", data.StartTime.Format("2006-01-02 15:04:05 MST")))
	}
	if !data.EndTime.IsZero() {
		b.WriteString(fmt.Sprintf("* **End Time:** %s\n", data.EndTime.Format("2006-01-02 15:04:05 MST")))
	}

	duration := data.Duration
	if duration == 0 && !data.StartTime.IsZero() && !data.EndTime.IsZero() {
		duration = data.EndTime.Sub(data.StartTime)
	}
	if duration > 0 {
		b.WriteString(fmt.Sprintf("* **Total Duration:** %s\n", formatDuration(duration)))
	}

	// Token usage
	tokenUsage := data.TokenUsage
	if tokenUsage == "" {
		tokenUsage = extractTokenUsage(data.OpenCodeOutput)
	}
	if tokenUsage != "" {
		b.WriteString(fmt.Sprintf("* **Token Usage:** %s\n", tokenUsage))
	} else if len(data.Prompt) > 0 || len(data.OpenCodeOutput) > 0 {
		b.WriteString(fmt.Sprintf("* **Context Size:** ~%d chars prompt / ~%d chars agent output\n", len(data.Prompt), len(data.OpenCodeOutput)))
	}

	return b.String()
}

func formatDuration(d time.Duration) string {
	d = d.Round(time.Second)
	m := d / time.Minute
	s := (d % time.Minute) / time.Second
	if m > 0 {
		return fmt.Sprintf("%dm %ds", m, s)
	}
	return fmt.Sprintf("%ds", s)
}

func extractTokenUsage(output string) string {
	lines := strings.Split(output, "\n")
	for _, line := range lines {
		lineTrim := strings.TrimSpace(line)
		lower := strings.ToLower(lineTrim)
		if strings.Contains(lower, "tokens:") || strings.Contains(lower, "token usage:") || strings.Contains(lower, "total tokens:") {
			return lineTrim
		}
	}
	return ""
}

func getResultString(exitCode int) string {
	if exitCode == 0 {
		return "Success"
	}
	return "Failure"
}

func formatCodeChanges(changes []CodeChange) string {
	if len(changes) == 0 {
		return "_No files were modified._\n"
	}
	var out string
	for _, c := range changes {
		out += fmt.Sprintf("* **File:** `%s`\n  * **Change:** %s\n", c.File, c.Description)
	}
	return out
}

func formatRecommendations(recs string, solved bool) string {
	if solved || recs == "" {
		return ""
	}
	return fmt.Sprintf("## Recommendations for Manual Remediation\n> [!IMPORTANT]\n> OpenCode was unable to solve the issue automatically. Here are the recommended manual steps:\n>\n%s\n", recs)
}
